# 이미지 생성
FROM coredns/coredns:1.12.0
USER root
#RUN echo "aibiz:x:1000:1000::/home/aibiz:/bin/sh" >> /etc/passwd
#RUN echo "aibiz:x:1000:" >> /etc/group
#RUN mkdir -p /home/aibiz
#RUN chown -R aibiz:aibiz /home/aibiz
#USER aibiz
