#PYTHON3.12
FROM python:3.12

# ubuntu:ubuntu --> aibiz:aibiz
USER root
RUN echo "aibiz:x:1000:1000::/home/aibiz:/bin/sh" >> /etc/passwd
RUN echo "aibiz:x:1000:" >> /etc/group
RUN mkdir -p /home/aibiz
RUN chown -R aibiz:aibiz /home/aibiz


# Install essential package
RUN apt-get update && apt-get install -y curl
RUN pip install --no-cache-dir  "fastapi[all]"  sqlalchemy

# 작업 디렉토리
WORKDIR /app
COPY app /app

RUN chown -R aibiz:aibiz /app

USER aibiz
