# UID를 1000으로 변경해서 aibiz와 일치시킴
FROM trinodb/trino:476
USER root
RUN echo "aibiz:x:1000:1000::/home/trino:/bin/sh" >> /etc/passwd
RUN echo "aibiz:x:1000:" >> /etc/group
RUN mkdir -p /home/aibiz
RUN chown -R aibiz:aibiz /home/aibiz
USER aibiz
