# UID를 1000으로 변경해서 aibiz와 일치시킴
FROM nvidia/dcgm-exporter:4.4.0-4.5.0-ubuntu22.04
USER root
RUN echo "aibiz:x:1000:1000::/home/aibiz:/bin/sh" >> /etc/passwd
RUN echo "aibiz:x:1000:" >> /etc/group
RUN mkdir -p /home/aibiz
RUN chown -R aibiz:aibiz /home/aibiz
#USER aibiz
