# 이미지 생성
FROM quay.io/minio/minio:RELEASE.2024-12-13T22-19-12Z
USER root
RUN echo "aibiz:x:1000:1000::/home/aibiz:/bin/sh" >> /etc/passwd
RUN echo "aibiz:x:1000:" >> /etc/group
RUN mkdir -p /home/aibiz
RUN chown -R aibiz:aibiz /home/aibiz
USER aibiz
